package regAid;


/**
 *
 * @author SHANE
 * 
 */
import java.util.*;
import java.io.*;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;


public class GUI extends javax.swing.JApplet 
{       
        boolean CSS1 = false;
        boolean BUS1 = false;
        boolean ENG1 = false;
        String classFileName = "src/regAid/ClassNames.txt";
        String infoFileName = "src/regAid/SyllabusInfo.txt";
        String classFileName2 = "src/regAid/ClassNames_1.txt";
        String infoFileName2 = "src/regAid/SyllabusInfo_1.txt";
        String classFileName3 = "src/regAid/ClassNames_2.txt";
        String infoFileName3 = "src/regAid/SyllabusInfo_2.txt";
        MajorArrayList CSS = new MajorArrayList(classFileName, infoFileName);
        MajorArrayList BUS = new MajorArrayList(classFileName2, infoFileName2);
        MajorArrayList ENG = new MajorArrayList(classFileName3, infoFileName3);
        
        buildList b1 = new buildList(CSS);
        buildList b2 = new buildList(BUS);
        buildList b3 = new buildList(ENG);

        public static void main(String[] args) {
        //... Create an initialize the applet.
        GUI theApplet = new GUI();
        theApplet.init();         // Needed if overridden in applet
        //theApplet.start();        // Needed if overridden in applet
        
        //... Create a window (JFrame) and make applet the content pane.
        JFrame window = new JFrame("Reg Aid Zero Feature Release");
        window.setContentPane(theApplet);
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.pack();              // Arrange the components.
        //System.out.println(theApplet.getSize());
        window.setVisible(true);    // Make the window visible.
    }
    /** Initializes the applet second */
    @Override
    public void init() 
    {
        setSize(800, 400);


  //      majorsJList.setVisible(false);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {

                public void run() {
                    initComponents();
                }
            });
        } 
        catch (Exception ex) 
        {
            ex.printStackTrace();
        }
        
        
  //      syllabusJTextArea.setText(m1.getIndex(1));
        
    }
    



    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        majorsJList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        syllabusJTextArea = new javax.swing.JTextArea();
        engineeringJButton = new javax.swing.JButton();
        cssJButton = new javax.swing.JButton();
        businessJButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitJMenuItem = new javax.swing.JMenuItem();

        setBackground(new java.awt.Color(204, 204, 204));
        setName("mainJApplet"); // NOI18N

        majorsJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                majorsJListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(majorsJList);

        syllabusJTextArea.setColumns(20);
        syllabusJTextArea.setRows(5);
        jScrollPane2.setViewportView(syllabusJTextArea);

        engineeringJButton.setText("Engineering");
        engineeringJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineeringJButtonActionPerformed(evt);
            }
        });

        cssJButton.setText("CSS");
        cssJButton.setPreferredSize(new java.awt.Dimension(89, 23));
        cssJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cssJButtonActionPerformed(evt);
            }
        });

        businessJButton.setText("Business");
        businessJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessJButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        exitJMenuItem.setText("Exit");
        exitJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitJMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitJMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(engineeringJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(cssJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(businessJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(businessJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cssJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(engineeringJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
public String readFromJARFile(String filename)
throws IOException
{
  InputStream is = getClass().getResourceAsStream(filename);
  InputStreamReader isr = new InputStreamReader(is);
  BufferedReader br = new BufferedReader(isr);
  StringBuffer sb = new StringBuffer();
  String line;
  while ((line = br.readLine()) != null) 
  {
    sb.append(line);
  }
  br.close();
  isr.close();
  is.close();
  return sb.toString();
}
private void majorsJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_majorsJListValueChanged
    int index = (majorsJList.getSelectedIndex());
    
    try
    {
        if (index == -1)
            throw new IndexOutOfBoundsException();
    }
    catch(IndexOutOfBoundsException e)
    {
        index = 0;
        majorsJList.setSelectedIndex(index);
    }
    

    if (BUS1 == true)
    syllabusJTextArea.setText(BUS.get(index).getDescription());
    if (CSS1 == true)
    syllabusJTextArea.setText(CSS.get(index).getDescription());
    if (ENG1 == true)
    syllabusJTextArea.setText(ENG.get(index).getDescription());
    

    
     

}//GEN-LAST:event_majorsJListValueChanged

private void businessJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessJButtonActionPerformed
   BUS1 = true;
   CSS1 = false;
   ENG1 = false;
   majorsJList.setListData(BUS.getNameArray());
   majorsJList.setSelectedIndex(1);

}//GEN-LAST:event_businessJButtonActionPerformed

private void cssJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cssJButtonActionPerformed
   BUS1 = false;
   CSS1 = true;
   ENG1 = false;
   majorsJList.setListData(CSS.getNameArray());
   majorsJList.setSelectedIndex(1);
}//GEN-LAST:event_cssJButtonActionPerformed

private void engineeringJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineeringJButtonActionPerformed
    BUS1 = false;
   CSS1 = false;
   ENG1 = true;
   majorsJList.setListData(ENG.getNameArray());
   majorsJList.setSelectedIndex(1);
}//GEN-LAST:event_engineeringJButtonActionPerformed

private void exitJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJMenuItemActionPerformed
    System.exit(0);
}//GEN-LAST:event_exitJMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton businessJButton;
    private javax.swing.JButton cssJButton;
    private javax.swing.JButton engineeringJButton;
    private javax.swing.JMenuItem exitJMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList majorsJList;
    private javax.swing.JTextArea syllabusJTextArea;
    // End of variables declaration//GEN-END:variables
}
