package regAid;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
/**
 *
 * @author Shane
 */
public class SearchForm extends javax.swing.JDialog 
{
    GUI gui2;
    String cssClassNames = "CSS_ClassNames.txt";
    String cssSyllabusInfo = "CSS_SyllabusInfo.txt";
    String busClassNames = "BUS_ClassNames.txt";
    String busSyllabusInfo = "BUS_SyllabusInfo.txt";
    String engClassNames = "ENG_ClassNames.txt";
    String engSyllabusInfo = "ENG_SyllabusInfo.txt";
    MajorArrayList CSS = new MajorArrayList(cssClassNames, cssSyllabusInfo);
    MajorArrayList BUS = new MajorArrayList(busClassNames, busSyllabusInfo);
    MajorArrayList ENG = new MajorArrayList(engClassNames, engSyllabusInfo);
    buildList b1 = new buildList(CSS);
    buildList b2 = new buildList(BUS);
    buildList b3 = new buildList(ENG);

    /** Creates new form SearchForm */
    public SearchForm(java.awt.Frame parent, boolean modal,
      GUI gui2) {
      super(parent, modal);
      setLocationRelativeTo(null);
      this.gui2 = gui2; // !!
      initComponents();
      setTitle("Search");
      this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/RegAid/UW_Icon.gif"));
      
   }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchTitleJLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        searchJTextField = new javax.swing.JTextField();
        searchJButton = new javax.swing.JButton();
        closeJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        searchTitleJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchTitleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        searchTitleJLabel.setText("<html>Enter One of the Following...<BR>Class Name,<BR>Class Type,<BR>Class Teacher,<BR> or Class Time</html>");

        jTextField1.setText("jTextField1");

        searchJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchJTextFieldActionPerformed(evt);
            }
        });

        searchJButton.setText("Search");
        searchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchJButtonActionPerformed(evt);
            }
        });

        closeJButton.setText("Close");
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(searchTitleJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchTitleJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(searchJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void searchJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchJTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_searchJTextFieldActionPerformed

private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
    setVisible(false);
}//GEN-LAST:event_closeJButtonActionPerformed

private void searchJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchJButtonActionPerformed

    try
    {
        //Verify input is not empty
        String searchName = searchJTextField.getText();
        if (searchName.trim().length() == 0)
            throw new NullPointerException();

      //  MajorArrayList[] lists = new MajorArrayList[3];
        MajorArrayList[] lists = new MajorArrayList[2];
        lists[0] = BUS;
        lists[1] = CSS;
    //    lists[2] = ENG;

    //    MajorArrayList search = new Search().Search(lists, 3, searchName);
        MajorArrayList search = new Search().Search(lists, 2, searchName);
        
        if(search.getSize() == 0)
            throw new Exception();
        
        gui2.displaySearchResults(search.getNameArray(), search.getDescriptionArray(), search.getSize());
        gui2.majorsJList.clearSelection();
        

        //set boolean in GUI to true
        setVisible(false);

    }
    catch (NullPointerException isnull)
    {
        JOptionPane.showMessageDialog(null, "Must enter text in search box", "Input Error",
            JOptionPane.WARNING_MESSAGE);
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null, "No Result Found", "Search Error",
            JOptionPane.WARNING_MESSAGE);
    }
}//GEN-LAST:event_searchJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeJButton;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton searchJButton;
    private javax.swing.JTextField searchJTextField;
    private javax.swing.JLabel searchTitleJLabel;
    // End of variables declaration//GEN-END:variables
}
